name: Sync

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:WuDg/AmazeCard.git
          destination-repo: git@gitee.com:WuDG/AmazeCard.git
      
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
            gitee-username: WuDG
            gitee-password: ${{ secrets.GITEE_PASSWORD }}
            gitee-repo: WuDG/AmazeCard